"""
guppy_to_ir.py — Lower a GuppyCircuit to QuantumIR JSON.

This module implements the lowering pass from our Python simulation of Guppy
circuits to the shared QuantumIR contract defined in ir/quantum_ir_schema.json.

Lowering strategy
-----------------
Guppy compiles to HUGR (Hierarchical Unified Graph Representation) — a DAG-based
IR with explicit data-flow edges between ports.  Our simulation records operations
in sequential order (like a tape), not as a DAG.  The lowering pass:

  1. Iterates over circ.ops in order.
  2. Converts each GuppyOp to its QIR dict representation.
  3. Computes resource estimates (gate_count, depth, t_count, width).
  4. Produces a QIR JSON document that EXPLICITLY lists unsupported semantics.

Unsupported semantics (always present in output)
-------------------------------------------------
- "HUGR graph structure (flattened to sequential ops)" — our simulation records
  ops as a list, not a data-flow graph.  Parallelism information is lost.
- "inductive type recursion (not representable in QIR v0.1)" — Guppy supports
  recursive types / pattern matching; QIR has no such concept.

Additional unsupported semantics may be included depending on circuit content.

Resource estimation
-------------------
gate_count : number of gate ops (excludes measure/barrier/reset)
depth      : estimated from a greedy per-qubit depth counter (conservative
             approximation of the actual topological-sort DAG depth)
t_count    : count of T and Tdg gates (fault-tolerant cost metric)
width      : maximum qubit index + 1 (circuit width)
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from .guppy_types import GuppyCircuit, GuppyOp


# ---------------------------------------------------------------------------
# QIR schema version
# ---------------------------------------------------------------------------

QIR_VERSION = "0.1.0"

# ---------------------------------------------------------------------------
# Gates that count as T for T-count purposes
# ---------------------------------------------------------------------------

T_GATE_NAMES = {"T", "Tdg"}

# CCX decomposes into 7 T gates in the standard Selinger decomposition.
CCX_T_COUNT = 7

# ---------------------------------------------------------------------------
# Main lowering entry point
# ---------------------------------------------------------------------------

def circuit_to_ir(
    circ: GuppyCircuit,
    extra_unsupported: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Lower a GuppyCircuit to a QuantumIR JSON-compatible dict.

    Parameters
    ----------
    circ              : GuppyCircuit to lower
    extra_unsupported : additional unsupported-semantics strings to include
                        (on top of the mandatory baseline list)

    Returns
    -------
    dict conforming to ir/quantum_ir_schema.json
    """
    ops_ir: List[Dict[str, Any]] = []
    for op in circ.ops:
        ops_ir.append(op.to_ir_dict())

    resources = _compute_resources(circ.ops, circ._next_qubit_id)

    # Mandatory unsupported list — NEVER empty for Guppy output.
    unsupported: List[str] = [
        "HUGR graph structure (flattened to sequential ops)",
        "inductive type recursion (not representable in QIR v0.1)",
    ]
    if extra_unsupported:
        unsupported.extend(extra_unsupported)

    # Detect additional unsupported patterns in this specific circuit.
    unsupported.extend(_detect_extra_unsupported(circ.ops))

    qir: Dict[str, Any] = {
        "version": QIR_VERSION,
        "source_lang": "guppy",
        "qubits": circ._next_qubit_id,
        "cbits": circ.n_cbits,
        "ops": ops_ir,
        "metadata": {
            "source_lang": "guppy",
            "version": QIR_VERSION,
            "unsupported": unsupported,
            "simulation_note": (
                "Generated by AGENT_02 (NETON) Guppy Python simulation — "
                "NOT the real guppylang compiler. "
                "No physical QPU execution."
            ),
        },
        "resources": resources,
    }
    return qir


def circuit_to_ir_json(
    circ: GuppyCircuit,
    extra_unsupported: Optional[List[str]] = None,
    indent: int = 2,
) -> str:
    """Lower to QIR and return a formatted JSON string."""
    return json.dumps(circuit_to_ir(circ, extra_unsupported), indent=indent)


# ---------------------------------------------------------------------------
# Resource estimation
# ---------------------------------------------------------------------------

def _compute_resources(ops: List[GuppyOp], total_qubits: int) -> Dict[str, int]:
    """Estimate circuit resources from the op list.

    gate_count
        Number of gate-type ops.

    depth
        Greedy per-qubit depth counter: for each gate op, depth =
        max(depth_so_far[q] for q in gate.qubits) + 1.
        This is a conservative approximation — it assumes all ops on the
        same qubit are serialised, but gates on disjoint qubits may
        execute in parallel.

    t_count
        Sum of T/Tdg gates + 7 * CCX gates (standard decomposition).

    width
        Total number of qubits allocated (initial + mid-circuit ancilla).
    """
    gate_count = 0
    t_count = 0

    # Per-qubit depth tracker
    qubit_depth: Dict[int, int] = {}
    circuit_depth = 0

    for op in ops:
        if op.op_type == "gate":
            gate_count += 1

            # T-count
            if op.name in T_GATE_NAMES:
                t_count += 1
            elif op.name == "CCX":
                t_count += CCX_T_COUNT

            # Depth update — critical-path through qubit lifetimes
            if op.qubit_ids:
                incoming = max(qubit_depth.get(q, 0) for q in op.qubit_ids)
                new_depth = incoming + 1
                for q in op.qubit_ids:
                    qubit_depth[q] = new_depth
                circuit_depth = max(circuit_depth, new_depth)

        elif op.op_type == "measure":
            # Measurement ends a qubit's quantum lifetime — contributes to depth
            q = op.qubit_ids[0]
            incoming = qubit_depth.get(q, 0)
            new_depth = incoming + 1
            qubit_depth[q] = new_depth
            circuit_depth = max(circuit_depth, new_depth)

    return {
        "gate_count": gate_count,
        "depth": circuit_depth,
        "t_count": t_count,
        "width": total_qubits,
    }


# ---------------------------------------------------------------------------
# Extra unsupported detector
# ---------------------------------------------------------------------------

def _detect_extra_unsupported(ops: List[GuppyOp]) -> List[str]:
    """Scan ops for semantics that warrant additional unsupported notes."""
    extra: List[str] = []
    has_ccx = any(op.name == "CCX" for op in ops if op.op_type == "gate")
    if has_ccx:
        extra.append(
            "CCX T-count approximation: recorded as single gate, "
            "actual T-gate decomposition (7T) not expanded in QIR v0.1"
        )
    has_rotations = any(
        op.name in {"Rx", "Ry", "Rz"} and op.params
        for op in ops if op.op_type == "gate"
    )
    if has_rotations:
        extra.append(
            "Continuous rotation parameters stored as float64; "
            "precision loss possible when synthesising to Clifford+T"
        )
    return extra


# ---------------------------------------------------------------------------
# Validation helper
# ---------------------------------------------------------------------------

def validate_ir(qir: Dict[str, Any]) -> List[str]:
    """Perform lightweight structural validation of a QIR dict.

    Returns a list of validation error strings (empty = valid).
    This is a Python-level check; full JSON Schema validation requires
    the `jsonschema` library.
    """
    errors: List[str] = []

    required_top = {"version", "source_lang", "qubits", "cbits", "ops", "metadata", "resources"}
    missing = required_top - set(qir.keys())
    if missing:
        errors.append(f"Missing required top-level keys: {sorted(missing)}")

    if qir.get("source_lang") != "guppy":
        errors.append(
            f"source_lang should be 'guppy', got {qir.get('source_lang')!r}"
        )

    meta = qir.get("metadata", {})
    if not isinstance(meta.get("unsupported"), list):
        errors.append("metadata.unsupported must be a list")
    elif len(meta.get("unsupported", [])) == 0:
        errors.append("metadata.unsupported must not be empty for Guppy QIR output")

    res = qir.get("resources", {})
    for k in ("gate_count", "depth", "t_count", "width"):
        if k not in res:
            errors.append(f"resources.{k} missing")
        elif not isinstance(res[k], int) or res[k] < 0:
            errors.append(f"resources.{k} must be a non-negative integer")

    return errors
